maps: &maps
  map_tiles_provider: "//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
  map_tiles_provider_attribution: "&copy; <a href=\"http://osm.org/copyright\">OpenStreetMap</a> contributors"

apis: &apis
  microsoft_api_key: <%= ENV["MICROSOFT_API_KEY"] %>
  census_api_end_point: ""
  census_api_institution_code: ""
  census_api_portal_name: ""
  census_api_user_code: ""
  sms_end_point:  ""
  sms_username: ""
  sms_password: ""

http_basic_auth: &http_basic_auth
  http_basic_auth: true

secret_key_base: &secret_key_base
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

storage: &storage
  s3:
    :access_key_id: <%= ENV["S3_ACCESS_KEY_ID"] %>
    :secret_access_key: <%= ENV["S3_SECRET_ACCESS_KEY"] %>
    # :region: <%= ENV["S3_REGION"] %>
    # :bucket: <%= ENV["S3_BUCKET"] %>
    :endpoint: <%= ENV["S3_ENDPOINT"] %>

development:
  http_basic_username: "dev"
  http_basic_password: "pass"
  <<: *secret_key_base
  <<: *maps
  <<: *storage

test:
  <<: *secret_key_base
  <<: *maps

staging:
  # secret_key_base: ""
  server_name: <%= ENV["SERVER_NAME"] %>
  # mailer_delivery_method: :smtp
  # smtp_settings:
  #   :address: "smtp.example.com"
  #   :port: 25
  #   :domain: "your_domain.com"
  #   :user_name: "<username>"
  #   :password: "<password>"
  #   :authentication: "plain"
  #   :enable_starttls_auto: true
  force_ssl: <%= ENV["FORCE_SSL"] %>
  delay_jobs: true
  email_interceptor_recipients: ""
  errbit_host: ""
  errbit_project_key: ""
  errbit_project_id: 1
  errbit_self_hosted_ssl: false
  http_basic_username: ""
  http_basic_password: ""
  managers_url: ""
  managers_application_key: ""
  <<: *secret_key_base
  <<: *maps
  <<: *apis

preproduction:
  # secret_key_base: ""
  server_name: <%= ENV["SERVER_NAME"] %>
  # mailer_delivery_method: :smtp
  # smtp_settings:
  #   :address: "smtp.example.com"
  #   :port: 25
  #   :domain: "your_domain.com"
  #   :user_name: "<username>"
  #   :password: "<password>"
  #   :authentication: "plain"
  #   :enable_starttls_auto: true
  force_ssl: <%= ENV["FORCE_SSL"] %>
  delay_jobs: true
  email_interceptor_recipients: ""
  errbit_host: ""
  errbit_project_key: ""
  errbit_project_id: 1
  errbit_self_hosted_ssl: false
  http_basic_username: ""
  http_basic_password: ""
  managers_url: ""
  managers_application_key: ""
  twitter_key: ""
  twitter_secret: ""
  facebook_key: ""
  facebook_secret: ""
  google_oauth2_key: ""
  google_oauth2_secret: ""
  <<: *secret_key_base
  <<: *maps
  <<: *apis

production:
  # secret_key_base: ""
  server_name: <%= ENV["SERVER_NAME"] %>
  mailer_delivery_method: :smtp
  smtp_settings:
    :address: <%= ENV["SMTP_HOST"] %>
    :port: <%= ENV["SMTP_PORT"] %>
    :domain: <%= ENV["SMTP_EMAIL_DOMAIN"] %>
    :user_name: <%= ENV["SMTP_EMAIL_USERNAME"] %>
    :password: <%= ENV["SMTP_EMAIL_PASSWORD"] %>
    :authentication: <%= ENV["SMTP_AUTHENTICATION"] %>
    :enable_starttls_auto: true
  force_ssl: <%= ENV["FORCE_SSL"] %>
  delay_jobs: false
  errbit_host: ""
  errbit_project_key: ""
  errbit_project_id: 1
  errbit_self_hosted_ssl: false
  http_basic_username: ""
  http_basic_password: ""
  managers_url: ""
  managers_application_key: ""
  twitter_key: <%= ENV["TWITTER_KEY"] %>
  twitter_secret: <%= ENV["TWITTER_SECRET"] %>
  facebook_key: <%= ENV["FACEBOOK_KEY"] %>
  facebook_secret: <%= ENV["FACEBOOK_SECRET"] %>
  google_oauth2_key: <%= ENV["GOOGLE_KEY"] %>
  google_oauth2_secret: <%= ENV["GOOGLE_SECRET"] %>
  wordpress_oauth2_key: ""
  wordpress_oauth2_secret: ""
  wordpress_oauth2_site: ""
  <<: *secret_key_base
  <<: *maps
  <<: *apis
  <<: *storage